# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbdd86cd2d9818630c02a09ff45aa778d131d5e2170e88b47b9150179e281fd4146769b859dd48472faf069386beb803a262f87f2b094231c7a97829965eb4b7

test:
  secret_key_base: 315995a74829eeae494c5dd379aa3e316e384930a7ff993e88f91b33c0777b3fca630bbc25285f89c372ea3f643edfb26f11b2cc6dba4f01ad0ca3331b4c2233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
